### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by selvasoft**
Updated README.md with clear instruction for android

### CODE REVIEW

**Comment by vegidio** [comment]
Wow, for some reason I completely missed this PR. I'm sorry @selvasoft. I will review it today

**Comment by selvasoft** [comment]
@vegidio any updates?

**Comment by vegidio** [comment]
@selvasoft Sorry. Main work is crazy those days so hardly have time for anything else :(
But thanks a lot for your contribution. It's merged now.

**Comment by selvasoft** [comment]
no worries man

**Pull request merged**
